// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsePresetMesssage } from "./UsePresetMesssage";

export type ClientToServerMessage = { "type": "UsePreset" } & UsePresetMesssage;
