// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectPreset } from "./EffectPreset";

export type EffectPresetList = { effects: Array<EffectPreset>, };
