// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectPreset } from "./EffectPreset";
import type { LightPosition } from "./LightPosition";

export type InitializeMessage = { light_positions: Array<LightPosition>, effect_presets: Array<EffectPreset>, };
