// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitializeMessage } from "./InitializeMessage";
import type { StatusUpdateMessage } from "./StatusUpdateMessage";
import type { SystemStatusUpdateMessage } from "./SystemStatusUpdateMessage";

export type ServerToClientMessage = { "type": "StatusUpdate" } & StatusUpdateMessage | { "type": "SystemStatusUpdate" } & SystemStatusUpdateMessage | { "type": "Initialize" } & InitializeMessage;
