// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitializeMessage } from "./InitializeMessage";
import type { LightPosition } from "./LightPosition";

export type ServerToClientMessage = { "type": "UpdatePixelData" } & Array<number> | { "type": "LightPositionsUpdate" } & Array<LightPosition> | { "type": "Initialize" } & InitializeMessage;
