// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusUpdateMessage = { frames: number, average_window: number, average_frame_time: number, max_frame_time: number, min_frame_time: number, debug_text: string, };
