// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemStatus = { global_cpu: number, free_memory: number, total_memory: number, used_swap: number, };
