[package]
name = "reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
reflection_derive = { path = "../reflection_derive" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
