/**
 * This file was generated by this project's reflection framework.
 * Don't edit it manually. 
 */

/**
 * Generated binding.
 * An additive compositor composites other effects together using additive blending.
 */
export type AdditiveCompositorEffect = { 
/**
 * The effects to be composited together. The output of every effect will be added together.
 */
effects: Array<AnyEffect> };

/**
 * Generated binding.
 * Tagged with "type".
 * A wrapper for any effect that can be rendered.
 * Used for serialization and deserialization.
 */
export type AnyEffect = { "type": "AdditiveCompositor" } & AdditiveCompositorEffect | { "type": "AlphaCompositor" } & AlphaCompositorEffect | { "type": "Stripe" } & StripeEffect | { "type": "MusicVisualizer" } & MusicVisualizerEffect | { "type": "Rotate" } & RotateEffect | { "type": "FlashingColor" } & FlashingColorEffect | { "type": "SolidColor" } & SolidColorEffect | { "type": "WebsocketInput" } & WebsocketInputEffect;

/**
 * Generated binding.
 * An alpha compositor composites other effects together using alpha blending.
 */
export type AlphaCompositorEffect = { 
/**
 * The effects to be composited together. The output of every effect will be composited based on their order and transparency.
 */
effects: Array<AnyEffect> };

/**
 * Generated binding.
 * The stripes effect renders a rotating pattern with stripes of color.
 */
export type StripeEffect = { 
/**
 * The width of each stripe in pixels.
 */
stripe_width: number, 
/**
 * The colors of the stripes.
 */
stripe_colors: Array<PixelColor>, 
/**
 * The speed of the rotation in pixels per second.
 */
speed: number };

/**
 * Generated binding.
 * A pixel is a single unit of color data with an alpha value.
 */
export type PixelColor = { r: number, g: number, b: number, alpha: number };

/**
 * Generated binding.
 * The music visualizer effect runs a TCP socket server that listens for
 * audio data from the music visualizer client. Then, it renders the audio
 * data as a visualizer.
 */
export type MusicVisualizerEffect = { 
/**
 * The UDP listener that listens for audio data from the music visualizer client.
 */
port: number };

/**
 * Generated binding.
 */
export type RotateEffect = { 
/**
 * The effect to rotate
 */
effect: AnyEffect, 
/**
 * The number of pixels to rotate the frame by
 */
rotation: number };

/**
 * Generated binding.
 */
export type FlashingColorEffect = { 
/**
 * The offset of the flashing effect, in seconds.
 */
offset: number, 
/**
 * The speed of the flashing effect, in Hz.
 */
speed: number, 
/**
 * The color of the first flashing color.
 */
color_a: PixelColor, 
/**
 * The color of the second flashing color.
 */
color_b: PixelColor };

/**
 * Generated binding.
 */
export type SolidColorEffect = { 
/**
 * The color of the effect.
 */
color: PixelColor, 
/**
 * The start pixel index of the effect.
 */
start: number, 
/**
 * The stop pixel index of the effect.
 */
stop: number };

/**
 * Generated binding.
 */
export type WebsocketInputEffect = {  };

/**
 * Generated binding.
 * Tagged with "type".
 * A wrapper for any temporary effect that can be rendered.
 * Used for serialization and deserialization.
 */
export type AnyTemporaryEffect = { "type": "TemporaryEffectWrapper" } & DurationTemporaryEffect;

/**
 * Generated binding.
 */
export type DurationTemporaryEffect = { duration: number, effect: AnyEffect };

