/**
 * This file was generated by this project's reflection framework.
 * Don't edit it manually. 
 */

/**
 * Generated binding.
 */
export type AnyEffect = any;

/**
 * Generated binding.
 */
export type AnyTemporaryEffect = any;

/**
 * Generated binding.
 */
export type MusicVisualizerEffect = any;

