// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The music visualizer effect runs a TCP socket server that listens for
 * audio data from the music visualizer client. Then, it renders the audio
 * data as a visualizer.
 */
export type MusicVisualizerEffect = { 
/**
 * The UDP listener that listens for audio data from the music visualizer client
 */
port: number, };
