// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pixel is a single unit of color data with an alpha value.
 */
export type Pixel = { r: number, g: number, b: number, alpha: number, };
