// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyEffect } from "./AnyEffect";

export type RotateEffect = { 
/**
 * The effect to rotate
 */
effect: AnyEffect, 
/**
 * The number of pixels to rotate the frame by
 */
rotation: number, };
