/**
 * This file was generated by this project's reflection framework.
 * Don't edit it manually. 
 */

/**
 * Generated binding.
 * An enum schema definition.
 */
export type EnumValue = { variants: Array<EnumVariant>, tag_name: string, content_subfield: string | null };

/**
 * Generated binding.
 * A variant in an enum schema definition.
 */
export type EnumVariant = { name: string, value: Schema | null };

/**
 * Generated binding.
 * Tagged with "type".
 * A schema definition for a type.
 */
export type Schema = { "type": "Struct", "content": Array<SchemaField> } | { "type": "Enum", "content": EnumValue } | { "type": "Optional", "content": Schema } | { "type": "ArrayOf", "content": Schema } | { "type": "TupleOf", "content": Array<Schema> } | { "type": "ObjectOf", "content": ObjectSchema } | { "type": "Reference", "content": string } | { "type": "Number" } | { "type": "String" } | { "type": "Boolean" };

/**
 * Generated binding.
 * A field in a schema definition.
 */
export type SchemaField = { name: string, ty: Schema, docs: string | null };

/**
 * Generated binding.
 * A schema definition for an arbitrary object type (hashmap).
 */
export type ObjectSchema = { key_schema: Schema, value_schema: Schema };

