// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyEffect } from "./AnyEffect";

/**
 * An additive compositor composites other effects together using additive blending.
 */
export type AdditiveCompositorEffect = { effects: Array<AnyEffect>, };
