// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyEffect } from "./AnyEffect";

/**
 * An alpha compositor composites other effects together using alpha blending.
 */
export type AlphaCompositorEffect = { effects: Array<AnyEffect>, };
