// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdditiveCompositorEffect } from "./AdditiveCompositorEffect";
import type { AlphaCompositorEffect } from "./AlphaCompositorEffect";
import type { FlashingColorEffect } from "./FlashingColorEffect";
import type { MusicVisualizerEffect } from "./MusicVisualizerEffect";
import type { RotateEffect } from "./RotateEffect";
import type { SolidColorEffect } from "./SolidColorEffect";
import type { StripeEffect } from "./StripeEffect";
import type { WebsocketInputEffect } from "./WebsocketInputEffect";

export type AnyEffect = { "type": "AdditiveCompositor" } & AdditiveCompositorEffect | { "type": "AlphaCompositor" } & AlphaCompositorEffect | { "type": "Stripe" } & StripeEffect | { "type": "MusicVisualizer" } & MusicVisualizerEffect | { "type": "Rotate" } & RotateEffect | { "type": "FlashingColor" } & FlashingColorEffect | { "type": "SolidColor" } & SolidColorEffect | { "type": "WebsocketInput" } & WebsocketInputEffect;
