// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyEffect } from "./AnyEffect";

export type DurationTemporaryEffect = { duration: number, effect: AnyEffect, };
