// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pixel } from "./Pixel";

export type FlashingColorEffect = { time: number, speed: number, color: Pixel, };
