// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stripes effect renders a rotating pattern with stripes of color.
 */
export type StripeEffect = { stripe_width: number, stripe_colors: Array<[number, number, number]>, speed: number, };
