/**
 * This file was generated by this project's reflection framework.
 * Don't edit it manually. 
 */

/**
 * Generated binding.
 * Tagged with "type".
 * A schema definition for a type.
 */
export type Schema = { "type": "Struct", "content": Array<SchemaField> } | { "type": "Enum", "content": Array<EnumVariant> } | { "type": "Optional", "content": Schema } | { "type": "ArrayOf", "content": Schema } | { "type": "TupleOf", "content": Array<Schema> } | { "type": "Reference", "content": string } | { "type": "Number" } | { "type": "String" } | { "type": "Boolean" };

/**
 * Generated binding.
 * A field in a schema definition.
 */
export type SchemaField = { name: string, ty: Schema };

/**
 * Generated binding.
 * A variant in an enum schema definition.
 */
export type EnumVariant = { name: string, value: Schema | null };

